/**
 * Seed: Sample promo codes
 */
exports.seed = async function (knex) {
  await knex('promo_codes').del();

  await knex('promo_codes').insert([
    {
      id: 1,
      code: 'WELCOME10',
      description: '10% off for new customers',
      discount_type: 'percentage',
      discount_value: 10.00,
      minimum_order_amount: 0.00,
      maximum_discount_amount: 50.00,
      usage_limit: 1000,
      usage_count: 0,
      is_active: true,
      starts_at: '2024-01-01 00:00:00',
      expires_at: '2099-12-31 23:59:59',
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 2,
      code: 'SAVE20',
      description: '20% off on orders over $100',
      discount_type: 'percentage',
      discount_value: 20.00,
      minimum_order_amount: 100.00,
      maximum_discount_amount: 100.00,
      usage_limit: 500,
      usage_count: 0,
      is_active: true,
      starts_at: '2024-01-01 00:00:00',
      expires_at: '2099-12-31 23:59:59',
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 3,
      code: 'FLAT15OFF',
      description: '$15 flat discount on any order',
      discount_type: 'fixed',
      discount_value: 15.00,
      minimum_order_amount: 50.00,
      maximum_discount_amount: null,
      usage_limit: null,
      usage_count: 0,
      is_active: true,
      starts_at: '2024-01-01 00:00:00',
      expires_at: '2099-12-31 23:59:59',
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 4,
      code: 'TECHSALE30',
      description: '30% off electronics — limited time',
      discount_type: 'percentage',
      discount_value: 30.00,
      minimum_order_amount: 200.00,
      maximum_discount_amount: 200.00,
      usage_limit: 200,
      usage_count: 0,
      is_active: true,
      starts_at: '2024-01-01 00:00:00',
      expires_at: '2025-12-31 23:59:59',
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      id: 5,
      code: 'EXPIRED2023',
      description: 'Expired promotional code (for testing)',
      discount_type: 'percentage',
      discount_value: 5.00,
      minimum_order_amount: 0.00,
      maximum_discount_amount: null,
      usage_limit: 100,
      usage_count: 100,
      is_active: false,
      starts_at: '2023-01-01 00:00:00',
      expires_at: '2023-12-31 23:59:59',
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
  ]);
};
